#!/bin/bash

INPUT=/tmp/mido-mario-$$-in
RESULT=/tmp/mido-mario-$$-out
LOG=/tmp/mido-mario-$$-log
cat > "${INPUT}"
"${0}-inner" "${INPUT}" "${RESULT}" &> "${LOG}"
RC=$?
if [ "${RC}" == "0" ]; then
    cat "${RESULT}"
else
    echo '{'
    echo '  "cniVersion": "0.1.0",'
    echo '  "code": ' "${RC},"
    echo '  "msg": "'"${0}-inner returned ${RC}"'",'
    echo -n '  "details": '
    echo $(jq -R -s . < "${LOG}")
    echo '}'
    exit "${RC}"
fi
